const cards = [  //Массив стандартных карточек
  { name: 'Эльбрус',
    link: './images/Elbrus.png',
    alt: 'Гора Эльбрус, Солнце скрылось за вершину'},
  { name: 'Коми',
    link: './images/Komi.png',
    alt: 'Коми, река, лес, Зима'},
  { name: 'Москва',
    link: './images/Moscow.png',
    alt: 'Москва, центр города, день, небоскрёбы'},
  { name: 'Санкт-Петербург',
    link: './images/Saint-Petersburg.png',
    alt: 'Санкт-Петербург, вечер, разведённый мост'},
  { name: 'Сочи',
    link: './images/Sochi.png',
    alt: 'Сочи, побережье, огни ночного города с высоты птичьего полёта'},
  { name: 'Владивосток',
    link: './images/Vladivostok.png',
    alt: 'Владивосток, день, люди смотрят на Золотой мост'},
]
